const { contextBridge, ipcRenderer } = require("electron");

const invoke = (channel, payload) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld("codexpro", {
  getStatus: () => invoke("codexpro:status"),
  controlServer: (action) => invoke("codexpro:control", action),
  copyText: (text) => invoke("codexpro:copy", text),
  rotateLink: () => invoke("codexpro:rotate-link"),
  listProjects: () => invoke("codexpro:projects"),
  checkProfile: (profileId) => invoke("codexpro:check-profile", profileId),
  setupProfile: (profileId) => invoke("codexpro:setup-profile", profileId),
  openProfileChat: (payload) => invoke("codexpro:open-profile-chat", payload),
  reloadProfiles: () => invoke("codexpro:reload-profiles"),
  getManagerSettings: () => invoke("codexpro:get-manager-settings"),
  saveManagerSettings: (patch) => invoke("codexpro:save-manager-settings", patch),
  createWorkerImagePack: (name) => invoke("codexpro:create-worker-image-pack", name),
  selectWorkerImagePack: (packId) => invoke("codexpro:select-worker-image-pack", packId),
  deleteWorkerImagePack: (packId) => invoke("codexpro:delete-worker-image-pack", packId),
  chooseWorkerImage: (payload) => invoke("codexpro:choose-worker-image", payload),
  resetWorkerImage: (payload) => invoke("codexpro:reset-worker-image", payload),
  resetManagerSettings: () => invoke("codexpro:reset-manager-settings"),
  getHeadlessWorkers: () => invoke("codexpro:headless-workers"),
  createHeadlessWorker: (payload) => invoke("codexpro:create-headless-worker", payload),
  syncHeadlessWorker: (workerId) => invoke("codexpro:sync-headless-worker", workerId),
  startHeadlessWorker: (workerId) => invoke("codexpro:start-headless-worker", workerId),
  stopHeadlessWorker: (workerId) => invoke("codexpro:stop-headless-worker", workerId),
  deleteHeadlessWorker: (workerId) => invoke("codexpro:delete-headless-worker", workerId),
  setHeadlessWorkerAutoStart: (payload) => invoke("codexpro:set-headless-worker-autostart", payload),
  chooseRequestFiles: () => invoke("codexpro:choose-request-files"),
  captureClipboardImage: () => invoke("codexpro:capture-clipboard-image"),
  sendProfileRequest: (payload) => invoke("codexpro:send-profile-request", payload),
  renameProfileChat: (payload) => invoke("codexpro:rename-profile-chat", payload),
  getProfileResponse: (payload) => invoke("codexpro:get-profile-response", payload),
  getRepoTaskStatus: (payload) => invoke("codexpro:get-repo-task-status", payload),
  chooseProject: () => invoke("codexpro:choose-project"),
  chooseWorkspaceTarget: (kind) => invoke("codexpro:choose-workspace-target", kind),
  addProject: (root) => invoke("codexpro:add-project", root),
  removeProject: (root) => invoke("codexpro:remove-project", root),
  inspectProject: (root) => invoke("codexpro:inspect-project", root),
  openFolder: (root) => invoke("codexpro:open-folder", root),
  openExternal: (url) => invoke("codexpro:open-external", url)
});
